### ISSUE TITLE
Download don't work

### ISSUE THREAD

**Issue by CkLeandro675** [pear-devs/pear-desktop#4038]
The download option don't work. This problem appears when I download a song or an album. But if the songs folder is created, but completely empty..

<img width="360" height="165" alt="Image" src="https://github.com/user-attachments/assets/574f8d2e-ed8f-4716-8f83-b5af3efe701f" />

<img width="559" height="319" alt="Image" src="https://github.com/user-attachments/assets/6c13c1e9-d3f6-4a85-882e-cc3dc2081866" />

**Comment by xLindj** [comment]
It hasn't been working for over a month

**Comment by xuqi1011** [comment]
<img width="474" height="214" alt="Image" src="https://github.com/user-attachments/assets/0105d309-8ad6-4033-9c02-2765aa18ec86" />

Please fix this ...!!

**Comment by Joey451-OG** [comment]
#3973 The bug has been fixed and will be shipped in the next version.

**Comment by Sxrdnx** [comment]
for mac, also don't work when i try to install from brew

**Comment by juliensoenen** [comment]
> [#3973](https://github.com/pear-devs/pear-desktop/pull/3973) The bug has been fixed and will be shipped in the next version.

When i build for ARM mac the fix does not work, still the same error

**Comment by Joey451-OG** [comment]
@spareinetrip I unfortnuately do not have an ARM mac to test on. Are you able to investigate?

**Comment by SamuelGadiel** [comment]
It's possible to install the cask with this command

`brew install --cask pear-devs/pear/pear-desktop`

Credits to @Mehoff for pointing the correct source for this.
https://github.com/pear-devs/pear-desktop/issues/4089#issuecomment-3696239662
